/**
 * `tamma init --full-stack`
 *
 * Generates Docker deployment files for running the full Tamma platform.
 * Writes docker-compose.yml (using pre-built GHCR images), .env,
 * init-db.sql, and nginx-dashboard.conf into the target directory.
 */
import { writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

export interface InitFullStackOptions {
  dir?: string;
  force?: boolean;
}

export async function initFullStackCommand(options: InitFullStackOptions): Promise<void> {
  const targetDir = options.dir ?? process.cwd();

  const composeFile = join(targetDir, 'docker-compose.yml');
  if (existsSync(composeFile) && !options.force) {
    console.log('docker-compose.yml already exists. Use --force to overwrite.');
    process.exit(1);
  }

  writeFileSync(composeFile, generateComposeFile());
  writeFileSync(join(targetDir, '.env'), generateEnvFile());
  writeFileSync(join(targetDir, 'init-db.sql'), generateInitDbSql());
  writeFileSync(join(targetDir, 'nginx-dashboard.conf'), generateNginxConf());

  console.log('\nGenerated deployment files:');
  console.log('  docker-compose.yml');
  console.log('  .env');
  console.log('  init-db.sql');
  console.log('  nginx-dashboard.conf');
  console.log('\nNext steps:');
  console.log('  1. Edit .env with your credentials');
  console.log('  2. docker compose up -d');
  console.log('  3. Open http://localhost:3001 for the dashboard');
}

// ---------------------------------------------------------------------------
// Template generators
// ---------------------------------------------------------------------------

function generateComposeFile(): string {
  return `# =============================================================================
# Tamma Platform — Docker Compose (pre-built GHCR images)
#
# Generated by: tamma init --full-stack
#
# Usage:
#   1. Edit .env with your credentials
#   2. docker compose up -d
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Infrastructure: PostgreSQL
  # ---------------------------------------------------------------------------
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-tamma}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: \${POSTGRES_DB:-tamma}
    volumes:
      - tamma-pg-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-tamma}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - tamma-net

  # ---------------------------------------------------------------------------
  # Infrastructure: RabbitMQ
  # ---------------------------------------------------------------------------
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: \${RABBITMQ_USER:-tamma}
      RABBITMQ_DEFAULT_PASS: \${RABBITMQ_PASSWORD:-tamma}
    volumes:
      - tamma-rmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tamma-net

  # ---------------------------------------------------------------------------
  # ELSA .NET Workflow Engine
  # ---------------------------------------------------------------------------
  elsa-server:
    image: ghcr.io/meywd/tamma-elsa:latest
    environment:
      ConnectionStrings__PostgreSql: "Host=postgres;Port=5432;Database=\${POSTGRES_DB:-tamma};Username=\${POSTGRES_USER:-tamma};Password=\${POSTGRES_PASSWORD}"
      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: \${RABBITMQ_USER:-tamma}
      RabbitMq__Password: \${RABBITMQ_PASSWORD:-tamma}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 5s
      start_period: 30s
      retries: 3
    ports:
      - "5000:5000"
    networks:
      - tamma-net

  # ---------------------------------------------------------------------------
  # Tamma .NET REST API (ELSA management)
  # ---------------------------------------------------------------------------
  tamma-api-dotnet:
    image: ghcr.io/meywd/tamma-api-dotnet:latest
    environment:
      ConnectionStrings__PostgreSql: "Host=postgres;Port=5432;Database=\${POSTGRES_DB:-tamma};Username=\${POSTGRES_USER:-tamma};Password=\${POSTGRES_PASSWORD}"
      ElsaServer__Url: http://elsa-server:5000
      TammaServer__Url: http://tamma-api:3100
    depends_on:
      elsa-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 5s
      start_period: 15s
      retries: 3
    ports:
      - "3000:3000"
    networks:
      - tamma-net

  # ---------------------------------------------------------------------------
  # Tamma TypeScript API (Fastify)
  # ---------------------------------------------------------------------------
  tamma-api:
    image: ghcr.io/meywd/tamma-api:latest
    environment:
      DATABASE_URL: "postgresql://\${POSTGRES_USER:-tamma}:\${POSTGRES_PASSWORD}@postgres:5432/\${POSTGRES_DB:-tamma}"
      GITHUB_TOKEN: \${GITHUB_TOKEN}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3100/health"]
      interval: 15s
      timeout: 5s
      start_period: 15s
      retries: 3
    ports:
      - "3100:3100"
    networks:
      - tamma-net

  # ---------------------------------------------------------------------------
  # Tamma Engine (autonomous issue processing)
  # ---------------------------------------------------------------------------
  tamma-engine:
    image: ghcr.io/meywd/tamma-engine:latest
    environment:
      GITHUB_TOKEN: \${GITHUB_TOKEN:?GITHUB_TOKEN is required}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:?ANTHROPIC_API_KEY is required}
      GITHUB_OWNER: \${GITHUB_OWNER:?GITHUB_OWNER is required}
      GITHUB_REPO: \${GITHUB_REPO:?GITHUB_REPO is required}
      DATABASE_URL: "postgresql://\${POSTGRES_USER:-tamma}:\${POSTGRES_PASSWORD}@postgres:5432/\${POSTGRES_DB:-tamma}"
    volumes:
      - tamma-engine-workdir:/home/tamma/workdir
    depends_on:
      tamma-api:
        condition: service_healthy
    networks:
      - tamma-net

  # ---------------------------------------------------------------------------
  # Tamma Dashboard (React SPA via nginx)
  # ---------------------------------------------------------------------------
  tamma-dashboard:
    image: ghcr.io/meywd/tamma-dashboard:latest
    volumes:
      - ./nginx-dashboard.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      tamma-api:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - tamma-net

# =============================================================================
# Volumes
# =============================================================================
volumes:
  tamma-pg-data:
  tamma-rmq-data:
  tamma-engine-workdir:

# =============================================================================
# Networks
# =============================================================================
networks:
  tamma-net:
    driver: bridge
`;
}

function generateEnvFile(): string {
  return `# Tamma Docker Compose — Environment Variables
# Fill in the required values before running docker compose up.

# ===== Required =====
POSTGRES_PASSWORD=changeme
GITHUB_TOKEN=ghp_xxxxxxxxxxxx
ANTHROPIC_API_KEY=sk-ant-xxxxxxxxxxxx
GITHUB_OWNER=your-github-org
GITHUB_REPO=your-repo-name

# ===== Optional (with defaults) =====
# POSTGRES_USER=tamma
# POSTGRES_DB=tamma
# RABBITMQ_USER=tamma
# RABBITMQ_PASSWORD=tamma
# LOG_LEVEL=info
`;
}

function generateInitDbSql(): string {
  return `-- =============================================================================
-- Tamma Database Initialization
--
-- Executed once by PostgreSQL on first container start via
-- docker-entrypoint-initdb.d. Creates schemas and extensions used by
-- the platform.
-- =============================================================================

-- Enable commonly used extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create schemas used by the platform
CREATE SCHEMA IF NOT EXISTS elsa;
CREATE SCHEMA IF NOT EXISTS tamma;

-- Grant permissions to the default application user
GRANT ALL ON SCHEMA elsa TO current_user;
GRANT ALL ON SCHEMA tamma TO current_user;
GRANT ALL ON SCHEMA public TO current_user;
`;
}

function generateNginxConf(): string {
  return `server {
    listen 3001;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # TypeScript API proxy
    location /api/ {
        proxy_pass http://tamma-api:3100/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # .NET ELSA API proxy
    location /elsa-api/ {
        proxy_pass http://tamma-api-dotnet:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Static asset caching
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
}
`;
}
