using System.Text.Json.Serialization;
using Elsa.Extensions;
using Elsa.Workflows;
using Elsa.Workflows.Activities.Flowchart.Attributes;
using Elsa.Workflows.Attributes;
using Elsa.Workflows.Models;
using Microsoft.Extensions.Logging;
using Tamma.Core.Interfaces;

namespace Tamma.Activities.ADL;

/// <summary>
/// Creates a pull request for the completed implementation.
/// Includes plan summary and test information in the PR body.
///
/// Outcomes:
///   - Created: PR created successfully
///   - Error: PR creation failed
/// </summary>
[Activity(
    "Tamma.ADL",
    "Create Pull Request",
    "Create a PR with implementation summary for review",
    Kind = ActivityKind.Task
)]
[FlowNode("Created", "Error")]
public class CreatePullRequestActivity : Activity
{
    private readonly ILogger<CreatePullRequestActivity>? _logger;
    private readonly IGitHubIntegrationService? _github;

    [Input(Description = "Repository in owner/repo format")]
    public Input<string> Repository { get; set; } = default!;

    [Input(Description = "Feature branch name")]
    public Input<string> BranchName { get; set; } = default!;

    [Input(Description = "Base branch to merge into")]
    public Input<string> BaseBranch { get; set; } = new("main");

    [Input(Description = "Issue number")]
    public Input<int> IssueNumber { get; set; } = default!;

    [Input(Description = "Issue title")]
    public Input<string> IssueTitle { get; set; } = default!;

    [Input(Description = "Plan summary JSON")]
    public Input<string?> PlanJson { get; set; } = default!;

    [Output(Description = "Created PR number")]
    public Output<int> PrNumber { get; set; } = default!;

    [Output(Description = "Created PR URL")]
    public Output<string?> PrUrl { get; set; } = default!;

    [JsonConstructor]
    public CreatePullRequestActivity() { }

    public CreatePullRequestActivity(
        ILogger<CreatePullRequestActivity> logger,
        IGitHubIntegrationService github)
    {
        _logger = logger;
        _github = github;
    }

    protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
    {
        var repository = Repository.Get(context);
        var branchName = BranchName.Get(context);
        var baseBranch = BaseBranch.Get(context);
        var issueNumber = IssueNumber.Get(context);
        var issueTitle = IssueTitle.Get(context) ?? "";
        var planJson = PlanJson.Get(context);

        try
        {
            var title = $"[ADL] #{issueNumber}: {issueTitle}";
            var body = BuildPrBody(issueNumber, planJson);

            var request = new CreatePullRequestRequest
            {
                Title = title,
                Body = body,
                Head = branchName,
                Base = baseBranch,
                Labels = new List<string> { "tamma-auto", "adl" }
            };

            var result = await _github!.CreateGitHubPullRequestAsync(repository, request);
            if (!result.Success)
            {
                _logger?.LogError("Failed to create PR: {Error}", result.Error);
                await context.CompleteActivityWithOutcomesAsync("Error");
                return;
            }

            PrNumber.Set(context, result.Data!.Number ?? 0);
            PrUrl.Set(context, result.Data.Url);

            _logger?.LogInformation("Created PR #{Number} for issue #{Issue}",
                result.Data.Number, issueNumber);
            await context.CompleteActivityWithOutcomesAsync("Created");
        }
        catch (Exception ex)
        {
            _logger?.LogError(ex, "Error creating PR for issue #{Number}", issueNumber);
            await context.CompleteActivityWithOutcomesAsync("Error");
        }
    }

    private static string BuildPrBody(int issueNumber, string? planJson)
    {
        var body = $"## Autonomous Development\n\nCloses #{issueNumber}\n\n";
        body += "This PR was generated by Tamma's Autonomous Development Loop (ADL).\n\n";

        if (!string.IsNullOrEmpty(planJson))
        {
            body += "### Implementation Plan\n\n";
            body += $"```json\n{planJson}\n```\n\n";
        }

        body += "---\n_Generated by Tamma ADL_\n";
        return body;
    }
}
