using System.Text.Json.Serialization;

namespace Tamma.Activities.Debug.Models;

/// <summary>
/// Debug entry context — determines which mode the debugging workflow uses.
/// </summary>
public enum DebugContext
{
    /// <summary>Tests failed during TDD GREEN phase — focus on making tests pass</summary>
    TddFailure,

    /// <summary>Unexpected runtime error during implementation — broader investigation</summary>
    RuntimeError,

    /// <summary>Pre-implementation bug investigation — investigate first, then fix (TDD for bugs)</summary>
    BugInvestigation
}

/// <summary>
/// Overall status of a debug session.
/// </summary>
public enum DebugStatus
{
    /// <summary>Bug was resolved successfully</summary>
    Resolved,

    /// <summary>Bug could not be resolved (internal — not surfaced to callers)</summary>
    Unresolved,

    /// <summary>Max iterations reached — actively escalated with full report</summary>
    Escalated
}

/// <summary>
/// Outcome of a single hypothesis after attempting a fix.
/// </summary>
public enum HypothesisOutcome
{
    /// <summary>Hypothesis has not been attempted yet</summary>
    Untried,

    /// <summary>Fix based on this hypothesis resolved the issue</summary>
    FixedIssue,

    /// <summary>Fix was applied but did not resolve the issue</summary>
    DidNotFix,

    /// <summary>Fix made the situation worse (more failures)</summary>
    MadeWorse
}

/// <summary>
/// A single root-cause hypothesis generated by the AI debugger.
/// </summary>
public class Hypothesis
{
    [JsonConstructor]
    public Hypothesis() { }

    /// <summary>Rank among all hypotheses (1 = highest confidence)</summary>
    public int Rank { get; set; }

    /// <summary>Human-readable description of the suspected root cause</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Confidence score (0.0 – 1.0)</summary>
    public decimal Confidence { get; set; }

    /// <summary>Suggested fix approach for this hypothesis</summary>
    public string SuggestedFix { get; set; } = string.Empty;

    /// <summary>Files/functions believed to be affected</summary>
    public List<string> AffectedFiles { get; set; } = new();

    /// <summary>Description of the fix that was attempted (null if untried)</summary>
    public string? FixAttempted { get; set; }

    /// <summary>Outcome after attempting the fix</summary>
    public HypothesisOutcome Outcome { get; set; } = HypothesisOutcome.Untried;

    /// <summary>Reason the fix failed (null if untried or succeeded)</summary>
    public string? FailureReason { get; set; }
}

/// <summary>
/// Record of a single fix attempt within the debug loop.
/// </summary>
public class FixAttempt
{
    [JsonConstructor]
    public FixAttempt() { }

    /// <summary>1-based iteration number</summary>
    public int Iteration { get; set; }

    /// <summary>The hypothesis being tested</summary>
    public string HypothesisDescription { get; set; } = string.Empty;

    /// <summary>Approach used for the fix</summary>
    public string Approach { get; set; } = string.Empty;

    /// <summary>Test result summary after the fix</summary>
    public string TestResult { get; set; } = string.Empty;

    /// <summary>Whether this attempt resolved the issue</summary>
    public bool Resolved { get; set; }

    /// <summary>Files modified by this fix attempt</summary>
    public List<string> FilesModified { get; set; } = new();

    /// <summary>Duration of this fix attempt</summary>
    public TimeSpan Duration { get; set; }

    /// <summary>Timestamp when attempt started</summary>
    public DateTime StartedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Comprehensive debug report generated on escalation.
/// </summary>
public class DebugReport
{
    [JsonConstructor]
    public DebugReport() { }

    /// <summary>All hypotheses generated during the session</summary>
    public List<Hypothesis> AllHypotheses { get; set; } = new();

    /// <summary>All fix attempts made</summary>
    public List<FixAttempt> AllAttempts { get; set; } = new();

    /// <summary>Test failures remaining after all attempts</summary>
    public List<string> RemainingFailures { get; set; } = new();

    /// <summary>All files investigated during debugging</summary>
    public List<string> FilesInvestigated { get; set; } = new();

    /// <summary>AI-generated suggested next steps for human developer</summary>
    public List<string> SuggestedNextSteps { get; set; } = new();

    /// <summary>Total time spent debugging</summary>
    public TimeSpan TotalDebugTime { get; set; }

    /// <summary>Formatted report text for human consumption</summary>
    public string ReportText { get; set; } = string.Empty;
}

/// <summary>
/// Final result of the debugging workflow.
/// </summary>
public class DebugResult
{
    [JsonConstructor]
    public DebugResult() { }

    /// <summary>Final status of the debug session</summary>
    public DebugStatus Status { get; set; }

    /// <summary>Identified root cause (empty if unresolved)</summary>
    public string RootCause { get; set; } = string.Empty;

    /// <summary>Description of the fix that was applied (empty if unresolved)</summary>
    public string FixApplied { get; set; } = string.Empty;

    /// <summary>Number of fix attempts made</summary>
    public int Attempts { get; set; }

    /// <summary>All hypotheses generated and their outcomes</summary>
    public List<Hypothesis> Hypotheses { get; set; } = new();

    /// <summary>Whether a regression test was added (BugInvestigation mode)</summary>
    public bool RegressionTestAdded { get; set; }

    /// <summary>Files modified by the successful fix</summary>
    public List<string> FilesChanged { get; set; } = new();

    /// <summary>Comprehensive debug report (especially for escalation)</summary>
    public string DebugReport { get; set; } = string.Empty;
}

/// <summary>
/// Collected error messages and stack traces for diagnosis.
/// </summary>
public class ErrorMessages
{
    [JsonConstructor]
    public ErrorMessages() { }

    /// <summary>Raw error output / stack traces</summary>
    public string RawOutput { get; set; } = string.Empty;

    /// <summary>Extracted individual error messages</summary>
    public List<string> Errors { get; set; } = new();

    /// <summary>Extracted stack traces</summary>
    public List<string> StackTraces { get; set; } = new();

    /// <summary>Log lines related to the error</summary>
    public List<string> RelevantLogLines { get; set; } = new();
}

/// <summary>
/// Relevant code context collected for diagnosis.
/// </summary>
public class RelevantCode
{
    [JsonConstructor]
    public RelevantCode() { }

    /// <summary>Files involved in the error</summary>
    public List<string> FilePaths { get; set; } = new();

    /// <summary>Code snippets from relevant files</summary>
    public List<CodeSnippet> Snippets { get; set; } = new();

    /// <summary>Recent changes to the relevant files</summary>
    public List<string> RecentChanges { get; set; } = new();
}

/// <summary>
/// A code snippet from a relevant file.
/// </summary>
public class CodeSnippet
{
    [JsonConstructor]
    public CodeSnippet() { }

    public string FilePath { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public int StartLine { get; set; }
    public int EndLine { get; set; }
}

/// <summary>
/// Git history context for diagnosis.
/// </summary>
public class GitHistoryContext
{
    [JsonConstructor]
    public GitHistoryContext() { }

    /// <summary>Recent commits on the branch</summary>
    public List<string> RecentCommits { get; set; } = new();

    /// <summary>Diff summary for recent changes</summary>
    public string DiffSummary { get; set; } = string.Empty;

    /// <summary>Blame information for error-related lines</summary>
    public List<string> BlameInfo { get; set; } = new();
}

/// <summary>
/// Test results collected for diagnosis.
/// </summary>
public class TestResultsContext
{
    [JsonConstructor]
    public TestResultsContext() { }

    /// <summary>Total number of tests</summary>
    public int TotalTests { get; set; }

    /// <summary>Number of passing tests</summary>
    public int PassingTests { get; set; }

    /// <summary>Number of failing tests</summary>
    public int FailingTests { get; set; }

    /// <summary>Detailed failing test info</summary>
    public List<string> FailingTestDetails { get; set; } = new();

    /// <summary>Coverage gaps (files with low coverage)</summary>
    public List<string> CoverageGaps { get; set; } = new();
}

/// <summary>
/// Reproduction steps extracted from issue description (BugInvestigation mode).
/// </summary>
public class ReproductionSteps
{
    [JsonConstructor]
    public ReproductionSteps() { }

    /// <summary>Ordered steps to reproduce the bug</summary>
    public List<string> Steps { get; set; } = new();

    /// <summary>Expected behavior from the issue</summary>
    public string ExpectedBehavior { get; set; } = string.Empty;

    /// <summary>Actual behavior reported</summary>
    public string ActualBehavior { get; set; } = string.Empty;

    /// <summary>Environment details if available</summary>
    public string Environment { get; set; } = string.Empty;
}

/// <summary>
/// Result of AI diagnosis: ranked hypotheses for root cause.
/// </summary>
public class DiagnosisResult
{
    [JsonConstructor]
    public DiagnosisResult() { }

    /// <summary>Ranked root cause hypotheses (highest confidence first)</summary>
    public List<Hypothesis> Hypotheses { get; set; } = new();

    /// <summary>Summary of the analysis</summary>
    public string AnalysisSummary { get; set; } = string.Empty;

    /// <summary>
    /// Machine-readable failure reason when the diagnosis did NOT produce a usable
    /// result (e.g. <see cref="DebugEvents.ReasonDiagnosisParseFailure"/> when the
    /// LLM reply was unparseable, <see cref="DebugEvents.ReasonDiagnosisCallFailed"/>
    /// when the mediated call itself failed). <c>null</c>/empty means the diagnosis
    /// ran to completion (its hypothesis list may still legitimately be empty).
    /// A failed diagnosis NEVER carries fabricated hypotheses — the caller gate in
    /// <c>DebuggingWorkflow</c> routes on this to DEBUG.DIAGNOSIS.FAILED.
    /// </summary>
    public string? FailureReason { get; set; }
}

/// <summary>
/// Result of writing a regression test.
/// </summary>
public class TestGenerationResult
{
    [JsonConstructor]
    public TestGenerationResult() { }

    /// <summary>Whether the test was successfully generated</summary>
    public bool Success { get; set; }

    /// <summary>Path to the generated test file</summary>
    public string TestFilePath { get; set; } = string.Empty;

    /// <summary>Name of the test method</summary>
    public string TestName { get; set; } = string.Empty;

    /// <summary>Whether the test fails as expected (reproduces the bug)</summary>
    public bool FailsAsExpected { get; set; }

    /// <summary>Error message if generation failed</summary>
    public string? ErrorMessage { get; set; }
}

/// <summary>
/// Accumulated context passed between debug loop iterations.
/// </summary>
public class DebugIterationContext
{
    [JsonConstructor]
    public DebugIterationContext() { }

    /// <summary>Current iteration number (1-based)</summary>
    public int CurrentIteration { get; set; }

    /// <summary>All hypotheses (updated with outcomes)</summary>
    public List<Hypothesis> Hypotheses { get; set; } = new();

    /// <summary>All fix attempts so far</summary>
    public List<FixAttempt> PreviousAttempts { get; set; } = new();

    /// <summary>Latest test results after most recent fix</summary>
    public string LatestTestResults { get; set; } = string.Empty;

    /// <summary>Latest error messages (may change after partial fix)</summary>
    public string LatestErrors { get; set; } = string.Empty;

    /// <summary>All files modified so far</summary>
    public List<string> AllFilesModified { get; set; } = new();

    /// <summary>Whether a regression test has been written (BugInvestigation)</summary>
    public bool RegressionTestWritten { get; set; }
}

/// <summary>
/// Resolution data recorded when a fix succeeds.
/// </summary>
public class ResolutionData
{
    [JsonConstructor]
    public ResolutionData() { }

    /// <summary>Root cause category for pattern analysis</summary>
    public string RootCauseCategory { get; set; } = string.Empty;

    /// <summary>Root cause description</summary>
    public string RootCause { get; set; } = string.Empty;

    /// <summary>Fix approach that worked</summary>
    public string FixApproach { get; set; } = string.Empty;

    /// <summary>Files involved in the fix</summary>
    public List<string> FilesInvolved { get; set; } = new();

    /// <summary>Total debugging time</summary>
    public TimeSpan DebuggingTime { get; set; }

    /// <summary>Number of attempts to resolution</summary>
    public int AttemptsToResolution { get; set; }

    /// <summary>Debug context mode</summary>
    public DebugContext Mode { get; set; }

    /// <summary>Story ID being debugged</summary>
    public string StoryId { get; set; } = string.Empty;
}
