using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Tamma.Data.Migrations.ControlPlane
{
    /// <summary>
    /// Story 5.6 + Story 1.5-37 (Wave C.1) — alert-system core schema.
    /// Introduces three CP-resident tables:
    /// <list type="bullet">
    ///   <item><description><c>alerts</c> — one row per raised alert, full
    ///     lifecycle (active → acknowledged → resolved).</description></item>
    ///   <item><description><c>alert_channels</c> — one row per delivery
    ///     target (email / Slack / PagerDuty / webhook). Credentials
    ///     live in Story 29-1's secret store, referenced via
    ///     <c>CredentialsSecretId</c>.</description></item>
    ///   <item><description><c>alert_delivery_attempts</c> — audit log of
    ///     every delivery try. <c>NotificationDispatcher</c> polls
    ///     <c>status IN ('pending','failed')</c> rows.</description></item>
    /// </list>
    ///
    /// <para>The migration skeleton auto-generated by <c>dotnet ef
    /// migrations add</c> included stray drift rows for
    /// <c>tenants</c>, <c>api_keys</c>, <c>platform_analytics_hourly</c>
    /// and <c>platform_api_key_index</c> because the root-level
    /// <c>ControlPlaneDbContextModelSnapshot.cs</c> was stale relative
    /// to earlier <c>Migrations/ControlPlane/</c> timestamps — those
    /// rows would re-apply no-op operations already present in the
    /// database. We hand-strip them here so the migration is narrowly
    /// scoped to the alert-system tables. The companion Designer file
    /// still carries the up-to-date full model snapshot so future
    /// <c>add-migration</c> runs see the complete surface.</para>
    /// </summary>
    /// <inheritdoc />
    public partial class AlertSystemCore : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "alert_channels",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false, defaultValueSql: "gen_random_uuid()"),
                    TenantId = table.Column<Guid>(type: "uuid", nullable: true),
                    Name = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    channel_type = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    IsEnabled = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true),
                    Config = table.Column<string>(type: "jsonb", nullable: false, defaultValueSql: "'{}'::jsonb"),
                    CredentialsSecretId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "now()"),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "now()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_alert_channels", x => x.Id);
                    table.CheckConstraint("CK_alert_channels_channel_type", "channel_type IN ('email','slack','pagerduty','webhook')");
                });

            migrationBuilder.CreateTable(
                name: "alerts",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false, defaultValueSql: "gen_random_uuid()"),
                    RuleId = table.Column<Guid>(type: "uuid", nullable: true),
                    Severity = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    Title = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false),
                    Description = table.Column<string>(type: "text", nullable: false),
                    CorrelationId = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    TenantId = table.Column<Guid>(type: "uuid", nullable: true),
                    Metadata = table.Column<string>(type: "jsonb", nullable: false, defaultValueSql: "'{}'::jsonb"),
                    Status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false, defaultValue: "active"),
                    AcknowledgedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    AcknowledgedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    ResolvedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    ResolvedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    Resolution = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "now()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_alerts", x => x.Id);
                    table.CheckConstraint("CK_alerts_severity", "\"Severity\" IN ('critical','warning','info')");
                    table.CheckConstraint("CK_alerts_status", "\"Status\" IN ('active','acknowledged','resolved')");
                });

            migrationBuilder.CreateTable(
                name: "alert_delivery_attempts",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false, defaultValueSql: "gen_random_uuid()"),
                    AlertId = table.Column<Guid>(type: "uuid", nullable: false),
                    ChannelId = table.Column<Guid>(type: "uuid", nullable: false),
                    AttemptNumber = table.Column<int>(type: "integer", nullable: false),
                    Status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false, defaultValue: "pending"),
                    Error = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true),
                    DeliveredAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    NextAttemptAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "now()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_alert_delivery_attempts", x => x.Id);
                    table.CheckConstraint("CK_alert_delivery_attempts_status", "\"Status\" IN ('pending','success','failed','dropped_rate_limit')");
                    table.ForeignKey(
                        name: "FK_alert_delivery_attempts_alert_channels_ChannelId",
                        column: x => x.ChannelId,
                        principalTable: "alert_channels",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_alert_delivery_attempts_alerts_AlertId",
                        column: x => x.AlertId,
                        principalTable: "alerts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_alert_channels_ChannelType_IsEnabled",
                table: "alert_channels",
                columns: new[] { "channel_type", "IsEnabled" });

            migrationBuilder.CreateIndex(
                name: "IX_alert_channels_TenantId_IsEnabled",
                table: "alert_channels",
                columns: new[] { "TenantId", "IsEnabled" });

            migrationBuilder.CreateIndex(
                name: "IX_alert_delivery_attempts_AlertId",
                table: "alert_delivery_attempts",
                column: "AlertId");

            migrationBuilder.CreateIndex(
                name: "IX_alert_delivery_attempts_ChannelId",
                table: "alert_delivery_attempts",
                column: "ChannelId");

            migrationBuilder.CreateIndex(
                name: "IX_alert_delivery_attempts_Status_CreatedAt",
                table: "alert_delivery_attempts",
                columns: new[] { "Status", "CreatedAt" },
                descending: new[] { false, true },
                filter: "\"Status\" IN ('pending','failed')");

            migrationBuilder.CreateIndex(
                name: "IX_alerts_CorrelationId",
                table: "alerts",
                column: "CorrelationId",
                filter: "\"CorrelationId\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_alerts_Severity_CreatedAt",
                table: "alerts",
                columns: new[] { "Severity", "CreatedAt" },
                descending: new[] { false, true });

            migrationBuilder.CreateIndex(
                name: "IX_alerts_Status_CreatedAt",
                table: "alerts",
                columns: new[] { "Status", "CreatedAt" },
                descending: new[] { false, true });

            migrationBuilder.CreateIndex(
                name: "IX_alerts_TenantId_CreatedAt",
                table: "alerts",
                columns: new[] { "TenantId", "CreatedAt" },
                descending: new[] { false, true },
                filter: "\"TenantId\" IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "alert_delivery_attempts");

            migrationBuilder.DropTable(
                name: "alert_channels");

            migrationBuilder.DropTable(
                name: "alerts");
        }
    }
}
