using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using Elsa.Extensions;
using Elsa.Workflows;
using Elsa.Workflows.Attributes;
using Elsa.Workflows.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Tamma.Activities.Testing.Models;

namespace Tamma.Activities.Testing;

/// <summary>
/// ELSA activity that commits auto-fixes generated by the LLM Call sub-workflow.
/// Tracks attempt number against max attempts (default 3) for the auto-fix loop.
/// </summary>
[Activity(
    "Tamma.Testing",
    "Commit Fix",
    "Commit auto-fix changes and track attempt count for the fix loop",
    Kind = ActivityKind.Task
)]
public class CommitFixActivity : CodeActivity<CommitFixResult>
{
    private readonly ILogger<CommitFixActivity>? _logger;
    private readonly IHttpClientFactory? _httpClientFactory;
    private readonly IConfiguration? _configuration;

    /// <summary>Mentorship session ID</summary>
    [Input(Description = "Mentorship session ID")]
    public Input<Guid> SessionId { get; set; } = default!;

    /// <summary>Repository URL or owner/repo</summary>
    [Input(Description = "Repository URL or owner/repo")]
    public Input<string> Repository { get; set; } = default!;

    /// <summary>Branch to commit to</summary>
    [Input(Description = "Branch name")]
    public Input<string> Branch { get; set; } = default!;

    /// <summary>The issues that were fixed</summary>
    [Input(Description = "Quality issues that were addressed by the fix")]
    public Input<List<QualityIssue>> FixedIssues { get; set; } = default!;

    /// <summary>Current attempt number (1-based)</summary>
    [Input(Description = "Current auto-fix attempt number", DefaultValue = 1)]
    public Input<int> AttemptNumber { get; set; } = new(1);

    /// <summary>Maximum number of auto-fix attempts</summary>
    [Input(Description = "Maximum auto-fix attempts", DefaultValue = 3)]
    public Input<int> MaxAttempts { get; set; } = new(3);

    /// <summary>Fix description from LLM</summary>
    [Input(Description = "Description of the fix applied")]
    public Input<string?> FixDescription { get; set; } = default!;

    [JsonConstructor]
    public CommitFixActivity()
    {
        _logger = null;
        _httpClientFactory = null;
        _configuration = null;
    }

    public CommitFixActivity(
        ILogger<CommitFixActivity> logger,
        IHttpClientFactory httpClientFactory,
        IConfiguration configuration)
    {
        _logger = logger;
        _httpClientFactory = httpClientFactory;
        _configuration = configuration;
    }

    protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
    {
        var sessionId = SessionId.Get(context);
        var repository = Repository.Get(context);
        var branch = Branch.Get(context);
        var fixedIssues = FixedIssues.Get(context) ?? new List<QualityIssue>();
        var attemptNumber = AttemptNumber.Get(context);
        var maxAttempts = MaxAttempts.Get(context);
        var fixDescription = FixDescription.GetOrDefault(context);

        _logger?.LogInformation(
            "Committing auto-fix attempt {Attempt}/{Max} for session {SessionId}",
            attemptNumber, maxAttempts, sessionId);

        try
        {
            // No mock path: simulated commits with random success rates and synthetic
            // commit SHAs were corrupting downstream audit events. All commits now
            // route through the real engine callback. See: feat/wave-b cleanup.
            var result = await CommitRealFix(
                sessionId, repository, branch, fixedIssues,
                attemptNumber, maxAttempts, fixDescription);

            _logger?.LogInformation(
                "Auto-fix commit attempt {Attempt}/{Max}: Success={Success}, ShouldRetry={ShouldRetry}",
                attemptNumber, maxAttempts, result.Success, result.ShouldRetry);

            context.SetResult(result);
        }
        catch (Exception ex)
        {
            _logger?.LogError(ex, "Failed to commit auto-fix for session {SessionId}", sessionId);

            context.SetResult(new CommitFixResult
            {
                Success = false,
                AttemptNumber = attemptNumber,
                MaxAttempts = maxAttempts,
                ShouldRetry = attemptNumber < maxAttempts,
                Error = $"Commit failed: {ex.Message}"
            });
        }
    }

    private async Task<CommitFixResult> CommitRealFix(
        Guid sessionId, string repository, string branch,
        List<QualityIssue> fixedIssues, int attemptNumber, int maxAttempts,
        string? fixDescription)
    {
        var callbackUrl = _configuration?["Engine:CallbackUrl"];
        if (string.IsNullOrEmpty(callbackUrl) || _httpClientFactory == null)
        {
            throw new InvalidOperationException(
                "Engine:CallbackUrl and HttpClientFactory are required for real commit");
        }

        var httpClient = _httpClientFactory.CreateClient();
        var commitMessage = GenerateCommitMessage(fixedIssues, attemptNumber, fixDescription);

        var requestBody = new
        {
            sessionId = sessionId.ToString(),
            repository,
            branch,
            commitMessage,
            attemptNumber,
            action = "commit-fix"
        };

        var response = await httpClient.PostAsJsonAsync(
            $"{callbackUrl.TrimEnd('/')}/api/engine/commit-fix", requestBody);
        response.EnsureSuccessStatusCode();

        var result = await response.Content.ReadFromJsonAsync<JsonElement>();

        return new CommitFixResult
        {
            Success = true,
            CommitSha = result.TryGetProperty("commitSha", out var sha)
                ? sha.GetString()
                : null,
            CommitMessage = commitMessage,
            FilesChanged = result.TryGetProperty("filesChanged", out var fc)
                ? fc.GetInt32()
                : 0,
            AttemptNumber = attemptNumber,
            MaxAttempts = maxAttempts,
            ShouldRetry = false, // Successful commit does not need retry
            FixedIssues = fixedIssues.Select(i => i.Message).ToList()
        };
    }

    private static string GenerateCommitMessage(
        List<QualityIssue> fixedIssues, int attemptNumber, string? fixDescription)
    {
        var issueCategories = fixedIssues
            .Select(i => i.Category)
            .Distinct()
            .Select(c => c.ToString().ToLowerInvariant())
            .ToList();

        var categories = issueCategories.Count > 0
            ? string.Join(", ", issueCategories)
            : "quality";

        var description = !string.IsNullOrEmpty(fixDescription)
            ? fixDescription
            : $"auto-fix {categories} issues";

        return $"fix: {description} (attempt {attemptNumber})";
    }
}
