using System.Text.Json;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;
using NUnit.Framework;
using Tamma.Activities.ADL;
using Tamma.Core.Interfaces;
using Tamma.Data.Entities;
using Tamma.Data.Repositories;

namespace Tamma.Activities.Tests.ADL;

/// <summary>
/// Story 2.8 build-out — unit coverage for the PR-creation activity's pure
/// helpers (body composition, deterministic fallback, smart labels, error
/// classification, change-summary derivation), the new <c>EmitPrEventActivity</c>
/// + the <c>PrEvents</c> DCB builder. Follows the codebase pattern of testing
/// the testable static logic (running a full Elsa ActivityExecutionContext is
/// avoided — see EmitCleanupTerminalEventActivityTests).
/// </summary>
[TestFixture]
public class PullRequestActivityTests
{
    // ================================================================
    // Constructors
    // ================================================================

    [Test]
    public void CreatePullRequestActivity_JsonConstructor_ShouldNotThrow()
    {
        Action act = () => new CreatePullRequestActivity();
        act.Should().NotThrow();
    }

    [Test]
    public void CreatePullRequestActivity_WithDependencies_ShouldNotThrow()
    {
        var logger = new Mock<ILogger<CreatePullRequestActivity>>();
        var github = new Mock<IGitHubIntegrationService>();
        Action act = () => new CreatePullRequestActivity(logger.Object, github.Object);
        act.Should().NotThrow();
    }

    [Test]
    public void EmitPrEventActivity_JsonConstructor_ShouldNotThrow()
    {
        Action act = () => new EmitPrEventActivity();
        act.Should().NotThrow();
    }

    [Test]
    public void EmitPrEventActivity_WithDependencies_ShouldNotThrow()
    {
        var logger = new Mock<ILogger<EmitPrEventActivity>>();
        var events = new Mock<IEventRepository>();
        Action act = () => new EmitPrEventActivity(logger.Object, events.Object);
        act.Should().NotThrow();
    }

    // ================================================================
    // BuildTitle
    // ================================================================

    [Test]
    public void BuildTitle_IncludesAdlPrefixAndIssueNumber()
    {
        CreatePullRequestActivity.BuildTitle(42, "Add auth")
            .Should().Be("[ADL] #42: Add auth");
    }

    [Test]
    public void BuildTitle_EmptyTitle_TrimsTrailingColon()
    {
        CreatePullRequestActivity.BuildTitle(7, "")
            .Should().Be("[ADL] #7");
    }

    // ================================================================
    // BuildBody — AI body path
    // ================================================================

    [Test]
    public void BuildBody_WithAiBody_UsesAiBodyAndAppendsSummaries()
    {
        var body = CreatePullRequestActivity.BuildBody(
            10, "## Summary\nAI text. Closes #10", planJson: null,
            changeSummary: null, testSummary: null);

        body.Should().Contain("AI text.");
        body.Should().Contain("## Change Summary");
        body.Should().Contain("## Test Results");
        body.Should().Contain("_Generated by Tamma ADL_");
        body.Should().NotBeNullOrWhiteSpace();
    }

    [Test]
    public void BuildBody_WithAiBodyMissingCloseKeyword_AddsCloses()
    {
        var body = CreatePullRequestActivity.BuildBody(
            55, "Some AI description without the keyword", planJson: null,
            changeSummary: null, testSummary: null);

        body.Should().Contain("Closes #55");
    }

    // ================================================================
    // BuildBody — fallback path (LLM unavailable)
    // ================================================================

    [Test]
    public void BuildBody_EmptyAiBody_ProducesDeterministicStructuredFallback()
    {
        var body = CreatePullRequestActivity.BuildBody(
            99, aiBody: "", planJson: "{\"steps\":[1,2]}",
            changeSummary: null, testSummary: null);

        // Never empty / plain — must carry the structured sections (FR-19e).
        body.Should().Contain("## Summary");
        body.Should().Contain("Closes #99");
        body.Should().Contain("## Changes");
        body.Should().Contain("## Testing");
        body.Should().Contain("## Breaking Changes");
        body.Should().Contain("## Migration");
        body.Should().Contain("## Checklist");
        body.Should().Contain("```json");
    }

    [Test]
    public void BuildFallbackBody_NeverEmpty_EvenWithNoInputs()
    {
        var body = CreatePullRequestActivity.BuildFallbackBody(1, null, null, null);
        body.Should().NotBeNullOrWhiteSpace();
        body.Should().Contain("## Summary");
        body.Should().Contain("No migration required.");
    }

    [Test]
    public void BuildFallbackBody_WithTestSummary_IncludesCoverage()
    {
        var test = new TestSummary { TestsRun = 10, TestsPassed = 9, Coverage = 87.5 };
        var body = CreatePullRequestActivity.BuildFallbackBody(1, null, null, test);
        body.Should().Contain("9/10 passed");
        body.Should().Contain("87.5%");
    }

    // ================================================================
    // Change-summary section (degrade vs render)
    // ================================================================

    [Test]
    public void BuildChangeSummarySection_Null_RendersUnavailableNote()
    {
        CreatePullRequestActivity.BuildChangeSummarySection(null)
            .Should().Contain("_Change summary unavailable._");
    }

    [Test]
    public void BuildChangeSummarySection_RendersCountsAndTopFiles()
    {
        var change = new ChangeSummary
        {
            FilesChanged = 3, FilesAdded = 1, FilesModified = 2, FilesDeleted = 0,
            LinesAdded = 120, LinesDeleted = 30, Commits = 4,
            TopFiles = new() { "src/a.cs", "src/b.cs" }
        };
        var section = CreatePullRequestActivity.BuildChangeSummarySection(change);
        section.Should().Contain("**Files changed:** 3");
        section.Should().Contain("+120 / -30");
        section.Should().Contain("**Commits:** 4");
        section.Should().Contain("`src/a.cs`");
    }

    [Test]
    public void BuildTestSummarySection_Null_RendersUnavailableNote()
    {
        CreatePullRequestActivity.BuildTestSummarySection(null)
            .Should().Contain("_Test summary unavailable._");
    }

    // ================================================================
    // ChangeSummary.FromChanges (reused Review logic)
    // ================================================================

    [Test]
    public void ChangeSummary_FromChanges_AggregatesAddedModifiedDeleted()
    {
        var changes = new List<GitHubFileChange>
        {
            new() { FilePath = "a.cs", ChangeType = "added", Additions = 50, Deletions = 0 },
            new() { FilePath = "b.cs", ChangeType = "modified", Additions = 10, Deletions = 5 },
            new() { FilePath = "c.cs", ChangeType = "removed", Additions = 0, Deletions = 40 },
        };

        var summary = ChangeSummary.FromChanges(changes, commitCount: 6);

        summary.FilesChanged.Should().Be(3);
        summary.FilesAdded.Should().Be(1);
        summary.FilesModified.Should().Be(1);
        summary.FilesDeleted.Should().Be(1);
        summary.LinesAdded.Should().Be(60);
        summary.LinesDeleted.Should().Be(45);
        summary.Commits.Should().Be(6);
        summary.TopFiles.Should().Contain("a.cs"); // most-changed first
    }

    // ================================================================
    // DetermineLabels — smart labels
    // ================================================================

    [Test]
    public void DetermineLabels_AlwaysIncludesAdlMarkers()
    {
        var labels = CreatePullRequestActivity.DetermineLabels(
            Array.Empty<string>(), changeSummary: null);
        labels.Should().Contain("tamma-auto");
        labels.Should().Contain("adl");
    }

    [Test]
    public void DetermineLabels_MapsIssueLabelsToPrLabels()
    {
        var labels = CreatePullRequestActivity.DetermineLabels(
            new[] { "bug", "security", "documentation" }, changeSummary: null);
        labels.Should().Contain("bugfix");
        labels.Should().Contain("security-review");
        labels.Should().Contain("documentation");
    }

    [Test]
    public void DetermineLabels_DerivesFromChangeType()
    {
        var change = new ChangeSummary { FilesChanged = 25, FilesAdded = 3, LinesAdded = 600 };
        var labels = CreatePullRequestActivity.DetermineLabels(
            Array.Empty<string>(), change);
        labels.Should().Contain("new-feature");
        labels.Should().Contain("large");
    }

    [Test]
    public void DetermineLabels_DeDupes()
    {
        var labels = CreatePullRequestActivity.DetermineLabels(
            new[] { "feature", "enhancement" }, changeSummary: null);
        labels.Should().OnlyHaveUniqueItems();
    }

    // ================================================================
    // Error classification — drives the failure edge
    // ================================================================

    [Test]
    public void ClassifyError_Permission()
    {
        CreatePullRequestActivity.ClassifyError("403 Forbidden").Should().Be("permission-denied");
        CreatePullRequestActivity.ClassifyError("Resource not accessible: permission")
            .Should().Be("permission-denied");
    }

    [Test]
    public void ClassifyError_AlreadyExists()
    {
        CreatePullRequestActivity.ClassifyError("422 A pull request already exists")
            .Should().Be("pr-already-exists");
    }

    [Test]
    public void ClassifyError_RateLimit()
    {
        CreatePullRequestActivity.ClassifyError("429 rate limit exceeded").Should().Be("rate-limited");
    }

    [Test]
    public void ClassifyError_GenericFallback()
    {
        CreatePullRequestActivity.ClassifyError(null).Should().Be("pr-creation-failed");
        CreatePullRequestActivity.ClassifyError("boom").Should().Be("pr-creation-failed");
    }

    [Test]
    public void IsAlreadyExistsError_DetectsKeywordAnd422()
    {
        CreatePullRequestActivity.IsAlreadyExistsError("A pull request already exists").Should().BeTrue();
        CreatePullRequestActivity.IsAlreadyExistsError("HTTP 422").Should().BeTrue();
        CreatePullRequestActivity.IsAlreadyExistsError("404 not found").Should().BeFalse();
    }

    // ================================================================
    // PrEvents — DCB builder
    // ================================================================

    [Test]
    public void PrEvents_BuildEvent_SetsTypeIssueAndTags()
    {
        var evt = PrEvents.BuildEvent(
            PrEvents.CreatedSuccess, issueNumber: 12, repository: "o/r",
            prNumber: 34, tenantId: null,
            data: new Dictionary<string, object?> { ["url"] = "https://x/pull/34", ["isDraft"] = true });

        evt.Type.Should().Be("PR.CREATED.SUCCESS");
        evt.IssueNumber.Should().Be(12);
        evt.Tags.Should().Contain("\"issueNumber\":\"12\"");
        evt.Tags.Should().Contain("\"repository\":\"o/r\"");
        evt.Tags.Should().Contain("\"prNumber\":\"34\"");
        evt.Data.Should().Contain("url");
        evt.Metadata.Should().Contain("eventSource");
    }

    [Test]
    public void PrEvents_BuildEvent_WithTenant_SetsTenantId()
    {
        var tenant = Guid.NewGuid();
        var evt = PrEvents.BuildEvent(PrEvents.CreatedFailed, 1, "o/r", tenantId: tenant);
        evt.TenantId.Should().Be(tenant);
        evt.Tags.Should().Contain(tenant.ToString());
    }

    [Test]
    public void PrEvents_BuildEvent_EmptyType_Throws()
    {
        Action act = () => PrEvents.BuildEvent("", 1, "o/r");
        act.Should().Throw<ArgumentException>();
    }

    [Test]
    public void PrEvents_ParseTenantId_HandlesEmptyAndValid()
    {
        PrEvents.ParseTenantId(null).Should().BeNull();
        PrEvents.ParseTenantId("").Should().BeNull();
        PrEvents.ParseTenantId("not-a-guid").Should().BeNull();
        var g = Guid.NewGuid();
        PrEvents.ParseTenantId(g.ToString()).Should().Be(g);
    }

    // ================================================================
    // EmitPrEventActivity.ParseData
    // ================================================================

    [Test]
    public void EmitPrEvent_ParseData_HandlesEmptyAndMalformed()
    {
        EmitPrEventActivity.ParseData(null).Should().BeNull();
        EmitPrEventActivity.ParseData("").Should().BeNull();
        EmitPrEventActivity.ParseData("{not json").Should().BeNull();
    }

    [Test]
    public void EmitPrEvent_ParseData_ParsesValidJson()
    {
        var data = EmitPrEventActivity.ParseData("{\"url\":\"x\",\"filesChanged\":3}");
        data.Should().NotBeNull();
        data!.Should().ContainKey("url");
        data.Should().ContainKey("filesChanged");
    }

    // ================================================================
    // Parsers
    // ================================================================

    [Test]
    public void ChangeSummary_Parse_RoundTrips()
    {
        var json = JsonSerializer.Serialize(new ChangeSummary { FilesChanged = 5, LinesAdded = 100 });
        var parsed = ChangeSummary.Parse(json);
        parsed.Should().NotBeNull();
        parsed!.FilesChanged.Should().Be(5);
        parsed.LinesAdded.Should().Be(100);
    }

    [Test]
    public void ChangeSummary_Parse_MalformedReturnsNull()
    {
        ChangeSummary.Parse("not json").Should().BeNull();
        ChangeSummary.Parse(null).Should().BeNull();
    }

    [Test]
    public void TestSummary_Parse_RoundTrips()
    {
        var json = JsonSerializer.Serialize(new TestSummary { TestsRun = 3, Coverage = 80 });
        var parsed = TestSummary.Parse(json);
        parsed!.TestsRun.Should().Be(3);
        parsed.Coverage.Should().Be(80);
    }

    // ================================================================
    // ExecuteCoreAsync — behavioral (happy / draft+ready / idempotency / failure)
    // ================================================================

    private static Mock<IGitHubIntegrationService> NoExistingPr()
    {
        var gh = new Mock<IGitHubIntegrationService>();
        gh.Setup(g => g.GetGitHubOpenPullRequestForBranchAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestRef?>.Ok(null));
        return gh;
    }

    private static CreatePullRequestRequest Req(bool draft = false) => new()
    {
        Title = "[ADL] #1: x", Body = "body", Head = "feature/1", Base = "main", IsDraft = draft
    };

    [Test]
    public async Task ExecuteCore_HappyPath_Ready_CreatesPr()
    {
        var gh = NoExistingPr();
        gh.Setup(g => g.CreateGitHubPullRequestAsync(It.IsAny<string>(), It.IsAny<CreatePullRequestRequest>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestResult>.Ok(
                new GitHubPullRequestResult { Success = true, Number = 7, Url = "https://x/pull/7" }));

        var outcome = await CreatePullRequestActivity.ExecuteCoreAsync(
            gh.Object, "o/r", "feature/1", "main", draft: false, Req());

        outcome.Outcome.Should().Be("Created");
        outcome.PrNumber.Should().Be(7);
        outcome.IsDraft.Should().BeFalse();
        outcome.Reused.Should().BeFalse();
    }

    [Test]
    public async Task ExecuteCore_HappyPath_Draft_ThreadsIsDraftToRequest()
    {
        var gh = NoExistingPr();
        CreatePullRequestRequest? captured = null;
        gh.Setup(g => g.CreateGitHubPullRequestAsync(It.IsAny<string>(), It.IsAny<CreatePullRequestRequest>()))
            .Callback<string, CreatePullRequestRequest>((_, r) => captured = r)
            .ReturnsAsync(IntegrationResult<GitHubPullRequestResult>.Ok(
                new GitHubPullRequestResult { Success = true, Number = 8, Url = "u" }));

        var outcome = await CreatePullRequestActivity.ExecuteCoreAsync(
            gh.Object, "o/r", "feature/1", "main", draft: true, Req(draft: true));

        outcome.Outcome.Should().Be("Created");
        outcome.IsDraft.Should().BeTrue();
        captured.Should().NotBeNull();
        captured!.IsDraft.Should().BeTrue("draft must be threaded into the create request");
    }

    [Test]
    public async Task ExecuteCore_ExistingOpenPr_ReusesAndUpdates_NoDoubleOpen()
    {
        var gh = new Mock<IGitHubIntegrationService>();
        gh.Setup(g => g.GetGitHubOpenPullRequestForBranchAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestRef?>.Ok(
                new GitHubPullRequestRef { Number = 42, Url = "https://x/pull/42", IsDraft = true }));
        gh.Setup(g => g.UpdateGitHubPullRequestAsync(It.IsAny<string>(), 42, It.IsAny<CreatePullRequestRequest>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestResult>.Ok(
                new GitHubPullRequestResult { Success = true, Number = 42, Url = "https://x/pull/42" }));

        var outcome = await CreatePullRequestActivity.ExecuteCoreAsync(
            gh.Object, "o/r", "feature/1", "main", draft: false, Req());

        outcome.Outcome.Should().Be("Updated");
        outcome.PrNumber.Should().Be(42);
        outcome.Reused.Should().BeTrue();
        // CRITICAL: a re-run must NOT open a second PR.
        gh.Verify(g => g.CreateGitHubPullRequestAsync(It.IsAny<string>(), It.IsAny<CreatePullRequestRequest>()), Times.Never);
    }

    [Test]
    public async Task ExecuteCore_CreateFailure_ReturnsError_NoFalseSuccess()
    {
        var gh = NoExistingPr();
        gh.Setup(g => g.CreateGitHubPullRequestAsync(It.IsAny<string>(), It.IsAny<CreatePullRequestRequest>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestResult>.Fail("403 Forbidden"));

        var outcome = await CreatePullRequestActivity.ExecuteCoreAsync(
            gh.Object, "o/r", "feature/1", "main", draft: false, Req());

        outcome.Outcome.Should().Be("Error");
        outcome.ErrorCode.Should().Be("permission-denied");
        outcome.PrNumber.Should().Be(0, "a failed create must not report a PR number (no false success)");
    }

    [Test]
    public async Task ExecuteCore_422Race_FallsBackToUpdate()
    {
        // Create returns 422-already-exists (a race), then the lookup finds it.
        var gh = new Mock<IGitHubIntegrationService>();
        var lookupCalls = 0;
        gh.Setup(g => g.GetGitHubOpenPullRequestForBranchAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>()))
            .ReturnsAsync(() =>
            {
                // First lookup: none. Second (post-422): found.
                lookupCalls++;
                return lookupCalls == 1
                    ? IntegrationResult<GitHubPullRequestRef?>.Ok(null)
                    : IntegrationResult<GitHubPullRequestRef?>.Ok(new GitHubPullRequestRef { Number = 99, Url = "u99" });
            });
        gh.Setup(g => g.CreateGitHubPullRequestAsync(It.IsAny<string>(), It.IsAny<CreatePullRequestRequest>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestResult>.Fail("422 A pull request already exists"));
        gh.Setup(g => g.UpdateGitHubPullRequestAsync(It.IsAny<string>(), 99, It.IsAny<CreatePullRequestRequest>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestResult>.Ok(
                new GitHubPullRequestResult { Success = true, Number = 99, Url = "u99" }));

        var outcome = await CreatePullRequestActivity.ExecuteCoreAsync(
            gh.Object, "o/r", "feature/1", "main", draft: false, Req());

        outcome.Outcome.Should().Be("Updated");
        outcome.PrNumber.Should().Be(99);
        outcome.Reused.Should().BeTrue();
    }

    [Test]
    public async Task ExecuteCore_UpdateFailureOnExisting_ReturnsError()
    {
        var gh = new Mock<IGitHubIntegrationService>();
        gh.Setup(g => g.GetGitHubOpenPullRequestForBranchAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestRef?>.Ok(new GitHubPullRequestRef { Number = 5, Url = "u5" }));
        gh.Setup(g => g.UpdateGitHubPullRequestAsync(It.IsAny<string>(), 5, It.IsAny<CreatePullRequestRequest>()))
            .ReturnsAsync(IntegrationResult<GitHubPullRequestResult>.Fail("429 rate limit"));

        var outcome = await CreatePullRequestActivity.ExecuteCoreAsync(
            gh.Object, "o/r", "feature/1", "main", draft: false, Req());

        outcome.Outcome.Should().Be("Error");
        outcome.ErrorCode.Should().Be("rate-limited");
    }

    [Test]
    public async Task ExecuteCore_ServiceThrows_ReturnsError_NeverThrows()
    {
        var gh = new Mock<IGitHubIntegrationService>();
        gh.Setup(g => g.GetGitHubOpenPullRequestForBranchAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>()))
            .ThrowsAsync(new HttpRequestException("network down"));

        var outcome = await CreatePullRequestActivity.ExecuteCoreAsync(
            gh.Object, "o/r", "feature/1", "main", draft: false, Req());

        outcome.Outcome.Should().Be("Error", "an exception must become an Error outcome, never a throw or false success");
    }
}
