using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tamma.Data.Entities;

/// <summary>
/// EF entity row for the <c>secrets</c> table introduced by Story
/// 29-2 (Postgres-backed secret cabinet). Holds metadata only — the
/// plaintext + ciphertext live on <see cref="SecretVersionRow"/>.
///
/// <para>The metadata facade <c>SecretMetadata</c> in
/// <c>Tamma.Api.Services.Secrets</c> is the public projection of
/// this row; field-by-field mapping happens inside the Story 29-2
/// repository so the EF layer does not leak into the
/// <c>ISecretStore</c> contract.</para>
///
/// <para>Lives on both the <c>ControlPlaneDbContext</c>
/// (platform-scope rows; <c>Scope='platform'</c>) and the
/// <c>TenantDbContext</c> (tenant-scope rows; <c>Scope='tenant'</c>).
/// Per Story 29-2 Doc-01 §1.2 the discriminator is implicit in the
/// connection: platform secrets live on <c>tamma_control</c>; tenant
/// secrets live on the per-tenant database. The
/// <see cref="Scope"/> column is therefore redundant on each DB but
/// kept for cross-DB reporting / migration safety.</para>
///
/// <para>Schema is pinned via DataAnnotations rather than a fluent
/// configuration so we can wire the entity into both
/// <see cref="ControlPlaneDbContext"/> and <see cref="TenantDbContext"/>
/// through partial-class <see cref="Microsoft.EntityFrameworkCore.DbSet{TEntity}"/>
/// properties without touching either context's primary
/// <c>OnModelCreating</c> file (Epic 28 owns those).</para>
/// </summary>
[Table("secrets")]
// Unique index is configured fluently in SecretsDbContext.OnModelCreating
// as (Scope, TenantId, Name) with NULLS NOT DISTINCT — a DataAnnotation
// [Index] cannot express NULLS NOT DISTINCT, which is required so
// platform-scope rows (TenantId = NULL) still collide on a duplicate name.
public class SecretRow
{
    /// <summary>
    /// Stable identifier — UUID v4 generated by Postgres
    /// (<c>gen_random_uuid()</c>).
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    /// <summary>
    /// Slug unique per <c>(scope, tenant_id?)</c> per Story 29-1 AC7.
    /// Lower-kebab-case with optional <c>/</c> separators (e.g.
    /// <c>db/app-role</c>).
    /// </summary>
    [Required]
    [MaxLength(255)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Scope — <c>"platform"</c> or <c>"tenant"</c>. Mirrors
    /// <c>Tamma.Api.Services.Secrets.SecretScope</c>; persisted as a
    /// short string so the schema is not coupled to a CLR enum
    /// ordering.
    /// </summary>
    [Required]
    [MaxLength(16)]
    public string Scope { get; set; } = "tenant";

    /// <summary>
    /// Owning tenant when <see cref="Scope"/> is <c>"tenant"</c>;
    /// null on the platform DB. Tenant DB rows always carry the
    /// owning tenant id even though the discriminator is implicit —
    /// keeps cross-DB exports unambiguous.
    /// </summary>
    public Guid? TenantId { get; set; }

    /// <summary>
    /// Typed purpose — drives default rotation cadence + admin-UI
    /// iconography. Persisted as a short string. See
    /// <c>Tamma.Api.Services.Secrets.SecretPurpose</c> for the
    /// enumeration.
    /// </summary>
    [Required]
    [MaxLength(40)]
    public string Purpose { get; set; } = "generic";

    /// <summary>
    /// Downstream consumer refs serialised as JSONB. Story 29-2
    /// repository projects this to / from
    /// <c>IReadOnlyList&lt;ConsumerRef&gt;</c>. Defaults to an empty
    /// JSON array.
    /// </summary>
    [Required]
    [Column("ConsumerRefs", TypeName = "jsonb")]
    public string ConsumerRefsJson { get; set; } = "[]";

    /// <summary>User id of the creator / last editor. Audit-only.</summary>
    public Guid OwnerUserId { get; set; }

    /// <summary>
    /// Rotation schedule serialised as JSONB. Story 29-2 repository
    /// projects this to / from
    /// <c>Tamma.Api.Services.Secrets.RotationSchedule</c>. Default is
    /// the JSON encoding of <c>RotationScheduleKind.None</c>.
    /// </summary>
    [Required]
    [Column("RotationSchedule", TypeName = "jsonb")]
    public string RotationScheduleJson { get; set; } = "{\"Kind\":\"None\"}";

    /// <summary>UTC timestamp of the last successful rotation.</summary>
    public DateTime? LastRotatedAt { get; set; }

    /// <summary>UTC timestamp when the next rotation is due.</summary>
    public DateTime? NextRotationDueAt { get; set; }

    /// <summary>
    /// Version number of the row currently in <c>active</c> status.
    /// Zero when no version has been minted yet.
    /// </summary>
    public int ActiveVersionNumber { get; set; }

    /// <summary>UTC create timestamp.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>UTC timestamp of the last metadata edit.</summary>
    public DateTime UpdatedAt { get; set; }
}
