using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Tamma.Data.Entities;

/// <summary>
/// EF entity row for the <c>secret_versions</c> table introduced by
/// Story 29-2 (Postgres-backed secret cabinet). One row per minted
/// version of a secret; the ciphertext column carries an envelope
/// blob produced by the Story 29-2 <c>SecretEnvelope</c> helper
/// (version byte + kek_id byte + 12-byte wrap nonce + 32-byte
/// AES-GCM-wrapped DEK + 16-byte wrap tag + 12-byte value nonce +
/// value ciphertext + 16-byte value tag).
///
/// <para>The plaintext payload is never stored on this entity; the
/// EF tracking layer never sees it. The
/// <c>PostgresSecretStoreBackend</c> writes/reads the
/// <see cref="Ciphertext"/> bytes directly, runs decryption out of
/// band, and returns plaintext to the facade — never via an EF
/// projection.</para>
///
/// <para>Status enum values mirror
/// <c>Tamma.Api.Services.Secrets.SecretVersionStatus</c> (Pending,
/// Active, RetiredGrace, Revoked) but the value is persisted as a
/// short string (max 16 chars) so the schema is not coupled to a CLR
/// enum ordering.</para>
///
/// <para>Lives on both the <c>ControlPlaneDbContext</c>
/// (platform-scope versions) and <c>TenantDbContext</c>
/// (tenant-scope versions). The discriminator is implicit in the
/// connection: platform-scope rows live on <c>tamma_control</c>;
/// tenant-scope rows live on the per-tenant database.</para>
/// </summary>
[Table("secret_versions")]
[Index(nameof(SecretId), nameof(VersionNumber), IsUnique = true)]
[Index(nameof(KekId))]
public class SecretVersionRow
{
    /// <summary>
    /// Surrogate row id. UUID v4 generated by Postgres
    /// (<c>gen_random_uuid()</c>).
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    /// <summary>
    /// FK to <see cref="SecretRow.Id"/>.
    /// </summary>
    public Guid SecretId { get; set; }

    /// <summary>
    /// Monotonic 1-based version number. Unique per
    /// <see cref="SecretId"/> — enforced by a composite unique index.
    /// </summary>
    public int VersionNumber { get; set; }

    /// <summary>
    /// Lifecycle status — one of <c>pending</c>, <c>active</c>,
    /// <c>retired_grace</c>, <c>revoked</c>. Stored lower-snake-case
    /// for hand-readability in psql.
    /// </summary>
    [Required]
    [MaxLength(16)]
    public string Status { get; set; } = "pending";

    /// <summary>
    /// AES-256-GCM envelope produced by the Story 29-2
    /// <c>SecretEnvelope</c> helper. Null when the version row has
    /// been scrubbed (status flipped to <c>revoked</c> via
    /// <c>DeleteVersionAsync</c>); the row is retained so audit
    /// queries still see that a version existed.
    /// </summary>
    [Column(TypeName = "bytea")]
    public byte[]? Ciphertext { get; set; }

    /// <summary>
    /// KEK slot used to wrap this version's DEK. Carried as a
    /// first-class column (in addition to the byte embedded in the
    /// envelope) so a rewrap pass can <c>WHERE KekId = old</c>
    /// without decrypting every row.
    /// </summary>
    [Column(TypeName = "smallint")]
    public byte KekId { get; set; }

    /// <summary>
    /// Envelope format version (matches the byte at offset 0 of
    /// <see cref="Ciphertext"/>). Carried as a column so a future
    /// migration can <c>WHERE FormatVersion &lt; n</c> without
    /// inspecting bytes.
    /// </summary>
    [Column(TypeName = "smallint")]
    public byte FormatVersion { get; set; }

    /// <summary>UTC timestamp when the version was minted.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>UTC timestamp when the version flipped to
    /// <c>active</c>. Null while still pending.</summary>
    public DateTime? ActivatedAt { get; set; }

    /// <summary>UTC timestamp when the version flipped to
    /// <c>retired_grace</c> or <c>revoked</c>. Null while still
    /// pending or active.</summary>
    public DateTime? RetiredAt { get; set; }

    /// <summary>User id of the operator (or system actor) that minted
    /// the version. <see cref="Guid.Empty"/> for system-initiated
    /// rotations (e.g. scheduled auto-rotation).</summary>
    public Guid CreatedByUserId { get; set; }
}
